# Generated by Django 4.1.3 on 2022-11-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_numberofsomemodelitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='numberofsomemodelitems',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
